from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected marker once, got {count}: {old[:80]!r}")
    p.write_text(text.replace(old, new, 1))


contract = "contracts/api-v1.json"
endpoint_marker = '''    {\n      "method": "POST",\n      "path": "/api/v1/files/upload-sessions",'''
endpoints = '''    {\n      "method": "GET",\n      "path": "/api/v1/examinee-groups",\n      "authenticated": true,\n      "idempotent": false\n    },\n    {\n      "method": "GET",\n      "path": "/api/v1/examinee-groups/:id",\n      "authenticated": true,\n      "idempotent": false\n    },\n    {\n      "method": "POST",\n      "path": "/api/v1/examinee-groups",\n      "authenticated": true,\n      "idempotent": true\n    },\n    {\n      "method": "PATCH",\n      "path": "/api/v1/examinee-groups/:id",\n      "authenticated": true,\n      "idempotent": true\n    },\n    {\n      "method": "DELETE",\n      "path": "/api/v1/examinee-groups/:id",\n      "authenticated": true,\n      "idempotent": true\n    },\n    {\n      "method": "GET",\n      "path": "/api/v1/examinees",\n      "authenticated": true,\n      "idempotent": false\n    },\n    {\n      "method": "GET",\n      "path": "/api/v1/examinees/by-identifier/:identifier",\n      "authenticated": true,\n      "idempotent": false\n    },\n    {\n      "method": "GET",\n      "path": "/api/v1/examinees/:id",\n      "authenticated": true,\n      "idempotent": false\n    },\n    {\n      "method": "POST",\n      "path": "/api/v1/examinees",\n      "authenticated": true,\n      "idempotent": true\n    },\n    {\n      "method": "PATCH",\n      "path": "/api/v1/examinees/:id",\n      "authenticated": true,\n      "idempotent": true\n    },\n    {\n      "method": "DELETE",\n      "path": "/api/v1/examinees/:id",\n      "authenticated": true,\n      "idempotent": true\n    },\n'''
replace_once(contract, endpoint_marker, endpoints + endpoint_marker)
replace_once(
    contract,
    '    "TestBookletStatus": ["enabled", "disabled"],\n    "FileStatus":',
    '    "TestBookletStatus": ["enabled", "disabled"],\n    "ExamineeStatus": ["enabled", "disabled"],\n    "FileStatus":',
)

request_schemas = '''    "CreateExamineeGroup": {\n      "parentId": { "type": "nullable-string", "required": false },\n      "name": { "type": "string", "required": true },\n      "proctorPassword": { "type": "nullable-string", "required": false },\n      "sortOrder": { "type": "nonnegative-integer", "required": false }\n    },\n    "UpdateExamineeGroup": {\n      "name": { "type": "string", "required": false },\n      "proctorPassword": { "type": "nullable-string", "required": false },\n      "sortOrder": { "type": "nonnegative-integer", "required": false },\n      "version": { "type": "positive-integer", "required": true }\n    },\n    "DeleteExamineeGroupQuery": {\n      "version": { "type": "positive-integer", "required": true }\n    },\n    "CreateExaminee": {\n      "groupId": { "type": "nullable-string", "required": false },\n      "code": { "type": "string", "required": true },\n      "identifier": { "type": "string", "required": true },\n      "name": { "type": "string", "required": true },\n      "note": { "type": "nullable-string", "required": false },\n      "status": { "type": "ExamineeStatus", "required": false }\n    },\n    "UpdateExaminee": {\n      "groupId": { "type": "nullable-string", "required": false },\n      "code": { "type": "string", "required": false },\n      "identifier": { "type": "string", "required": false },\n      "name": { "type": "string", "required": false },\n      "note": { "type": "nullable-string", "required": false },\n      "status": { "type": "ExamineeStatus", "required": false },\n      "version": { "type": "positive-integer", "required": true }\n    },\n    "DeleteExamineeQuery": {\n      "version": { "type": "positive-integer", "required": true }\n    },\n'''
replace_once(contract, '    "Login": {', request_schemas + '    "Login": {')

responses = '''    "ExamineeGroup": {\n      "id": { "type": "string", "required": true },\n      "tenantId": { "type": "string", "required": true },\n      "parentId": { "type": "nullable-string", "required": true },\n      "name": { "type": "string", "required": true },\n      "proctorPassword": { "type": "nullable-string", "required": true },\n      "sortOrder": { "type": "nonnegative-integer", "required": true },\n      "version": { "type": "positive-integer", "required": true },\n      "createdAt": { "type": "iso-string", "required": true },\n      "updatedAt": { "type": "iso-string", "required": true },\n      "deletedAt": { "type": "nullable-iso-string", "required": true }\n    },\n    "Examinee": {\n      "id": { "type": "string", "required": true },\n      "tenantId": { "type": "string", "required": true },\n      "groupId": { "type": "nullable-string", "required": true },\n      "createdBy": { "type": "string", "required": true },\n      "code": { "type": "string", "required": true },\n      "identifier": { "type": "string", "required": true },\n      "name": { "type": "string", "required": true },\n      "note": { "type": "nullable-string", "required": true },\n      "status": { "type": "ExamineeStatus", "required": true },\n      "version": { "type": "positive-integer", "required": true },\n      "createdAt": { "type": "iso-string", "required": true },\n      "updatedAt": { "type": "iso-string", "required": true },\n      "deletedAt": { "type": "nullable-iso-string", "required": true }\n    },\n'''
replace_once(contract, '    "FileMetadata": {', responses + '    "FileMetadata": {')

fixtures = "contracts/api-v1-fixtures.json"
fixture_entries = '''  "CreateExamineeGroupSchema": {\n    "parentId": null,\n    "name": "Fixture examinee group",\n    "proctorPassword": "proctor-1234",\n    "sortOrder": 0\n  },\n  "UpdateExamineeGroupSchema": {\n    "name": "Updated examinee group",\n    "version": 1\n  },\n  "DeleteExamineeGroupQuerySchema": { "version": "1" },\n  "ExamineeGroupSchema": {\n    "id": "examinee-group-1",\n    "tenantId": "company-opaque",\n    "parentId": null,\n    "name": "Fixture examinee group",\n    "proctorPassword": "proctor-1234",\n    "sortOrder": 0,\n    "version": 1,\n    "createdAt": "2026-08-16T00:00:00.000Z",\n    "updatedAt": "2026-08-16T00:00:00.000Z",\n    "deletedAt": null\n  },\n  "CreateExamineeSchema": {\n    "groupId": "examinee-group-1",\n    "code": "readable-code",\n    "identifier": "student-001",\n    "name": "Fixture examinee",\n    "note": null,\n    "status": "enabled"\n  },\n  "UpdateExamineeSchema": { "name": "Updated examinee", "version": 1 },\n  "DeleteExamineeQuerySchema": { "version": "1" },\n  "ExamineeSchema": {\n    "id": "examinee-1",\n    "tenantId": "company-opaque",\n    "groupId": "examinee-group-1",\n    "createdBy": "user-1",\n    "code": "readable-code",\n    "identifier": "student-001",\n    "name": "Fixture examinee",\n    "note": null,\n    "status": "enabled",\n    "version": 1,\n    "createdAt": "2026-08-16T00:00:00.000Z",\n    "updatedAt": "2026-08-16T00:00:00.000Z",\n    "deletedAt": null\n  },\n'''
replace_once(fixtures, '  "FileMetadataSchema": {', fixture_entries + '  "FileMetadataSchema": {')
